name: frontend_app
services:
  frontend_app:
    build:
        context: .
        dockerfile: Dockerfile
    image: frontend-app
    container_name: frontend_app
    network_mode: host
    restart: always
    # ports:
    #     - 20001:20001
      