name: backend_app
services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    container_name: backend_app
    image: backend-app
    restart: always
    volumes:
      - ./config.toml:/app/config.toml
    # ports:
      # - "8000:8000"